"""initial migration

Revision ID: 4cb9e696b687
Revises: 
Create Date: 2026-05-18 11:19:48.009327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb9e696b687'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_table('workers')
    op.add_column('clients', sa.Column('company_name', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'clients', 'companies', ['company_id'], ['id'])
    op.drop_column('clients', 'status')
    op.drop_column('clients', 'budget')
    op.drop_column('clients', 'project')
    op.drop_column('clients', 'company')
    op.add_column('employees', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'companies', ['company_id'], ['id'])
    op.add_column('projects', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'companies', ['company_id'], ['id'])
    op.add_column('tasks', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'companies', ['company_id'], ['id'])
    op.add_column('teams', sa.Column('name', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('department', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('leader_name', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'companies', ['company_id'], ['id'])
    op.drop_column('teams', 'project_name')
    op.drop_column('teams', 'role')
    op.drop_column('teams', 'employee_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('employee_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'company_id')
    op.drop_column('teams', 'leader_name')
    op.drop_column('teams', 'department')
    op.drop_column('teams', 'name')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'company_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'company_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'company_id')
    op.add_column('clients', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('budget', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('clients', 'company_id')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'company_name')
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hourly_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('availability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workers_pkey'))
    )
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    # ### end Alembic commands ###
